plan/urls.py
from django.urls import path

from plan.views import TaskCreateView, TaskListView, TagListView, TaskUpdateView, TagCreateView, TagUpdateView, \
    TaskDeleteView, TagDeleteView, toggle_assign_to_tag

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path(
            "tags/<int:pk>/toggle-assign/",
            toggle_assign_to_tag,
            name="toggle-assign",
        ),
]

app_name = "plan"

todo_list_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("plan.urls", namespace="plan")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

plan/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    creation = models.DateTimeField()
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["-creation"]

    def __str__(self):
        return f"{self.content} ({self.creation})"

plan/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from plan.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    success_url = reverse_lazy("plan:task-list")


class TaskCreateView(generic.CreateView):
    model = Task
    fields = ["content", "deadline", "tags"]
    success_url = reverse_lazy("plan:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("plan:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("plan:task-list")


class TagListView(generic.ListView):
    model = Tag
    success_url = reverse_lazy("plan:tag-list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("plan:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("plan:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("plan:tag-list")


def toggle_assign_to_tag(request, pk):
    task = Task.objects.get(id=pk)
    if task.is_done:
        task.is_done = False
    else:
        task.is_done = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("plan:task-list", args=[pk]))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'plan:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'plan:tag-list' %}">Tags</a></li>
</ul>

templates/plan/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/plan/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/plan/tag_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'plan:tag-create' %}" class="float-right btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'plan:tag-update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'plan:tag-delete' pk=tag.id %}" class="btn btn-secondary">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/plan/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>

templates/plan/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/plan/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      TODO list
    <a href="{% url 'plan:task-create' %}" class="float-right btn btn-primary">Add task</a>
    </h1>
<hr>

    <div class="ml-3">

    {% if task_list %}
    {% for task in task_list %}

      <h4>
        <strong>
        {{ task.content }}
        {% if task.is_done %}
          <span style="color: forestgreen">Done</span>
          <a href="{% url 'plan:toggle-assign' pk=task.id %}" class="float-right btn btn-secondary">
            Undo
          </a>
          {% else %}
          <span style="color: red">Not Done</span>
          <a href="{% url 'plan:toggle-assign' pk=task.id %}" class="float-right btn btn-success">
            Complete
          </a>
        {% endif %}
        </strong>
      </h4>

      <p><strong>Created:</strong> {{ task.creation }}
      {% if task.deadline %}
        Deadline: {{ task.deadline }}
      {% endif %}
      </p>

      <p class="text-muted"><strong>Tags:</strong>
      {% for tag in task.tags.all %}
        {{ tag.name }}
      {% endfor %}
      <a href="{% url 'plan:task-update' pk=task.id %}">
                Update
      </a>
      <a href="{% url 'plan:task-delete' pk=task.id %}">
                Delete
      </a>
      </p>

      <hr>
    {% endfor %}

    {% endif %}
  </div>
{% endblock %}